apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine

---

apiVersion: v1
kind: Service
metadata:
  name: My-service
  labels:
    app: front
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetePort: 80